---
title: "Link between FishLine and sampling designs"
author: "Kirsten Birch Håkansson, DTU Aqua"
date: \today
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, fig.width = 8, fig.height = 8, dpi = 900, dev = 'jpeg', results = 'asis')

library(RODBC)
library(sqldf)
library(dplyr)
library(knitr)
library(lubridate)
library(RColorBrewer)
library(viridis)
library(ggplot2)
library(readxl)

years <- c(2018:2020)
cruises <- c("MON", "SEAS", "IN-LYNG", "IN-HIRT")

output_path <- "Q:/mynd/kibi/RDBES/create_RDBES_data/references/"

lh_path <- "Q:/dfad/data/Data/Lykkehjul/Listerne/"

lh_18_name <- "DataFrames_Strata_2018_19DEC17.xlsx"
lh_19_name <- "observer_at_sea_2018-12-21.xlsx"
lh_20_name <- "observer_at_sea_sampling_frame_2019-12-16.xlsx"

```

```{r get_data, include=F}

design <- read.csv(paste0(output_path, "sampling_designs.csv"), sep = ";")

# Get data from FishLine ----

channel <- odbcConnect("FishLineDW")
    samp <- sqlQuery(
      channel,
      paste(
        "SELECT Trip.tripId, Trip.cruiseId, Trip.year, Trip.cruise, Trip.trip, Trip.tripType, Trip.logBldNr, Trip.timeZone, Trip.dateStart,                        Trip.dateEnd, Trip.samplingType, Trip.samplingMethod, Trip.fisheryType, Trip.platform1, Trip.nationalityPlatform1, 
                  Trip.fDFVesselPlatform1, Trip.nationalityPlatform2, Trip.platform2, Trip.dateSample, Trip.harbourSample,                                         Trip.nationalityHarbourSample, Trip.harbourLanding, Trip.nationalityHarbourLanding, Sample.sampleId, Sample.station, 
                  Sample.gearQuality, Sample.dfuArea, Sample.targetSpecies1, Sample.catchRegistration, Sample.speciesRegistration,                                 SpeciesListRaised.speciesCode, SpeciesListRaised.landingCategory, SpeciesListRaised.weightSubSample, 
                  SpeciesListRaised.weightTotal
         FROM     SpeciesListRaised LEFT OUTER JOIN
                  Sample ON SpeciesListRaised.sampleId = Sample.sampleId RIGHT OUTER JOIN
                  Trip ON Sample.tripId = Trip.tripId
         WHERE (Trip.year between ", min(years), " and ", max(years) , ")
                and Trip.cruise in ('", paste(cruises, collapse = "','"),
        "')",
        sep = ""
      )
    )
close(channel)

# Get lykkehjul ----

lh_18 <- read_xlsx(paste0(lh_path, lh_18_name), sheet = 1)
lh_19 <- read_xlsx(paste0(lh_path, lh_19_name), sheet = 1)
lh_20 <- read_xlsx(paste0(lh_path, lh_20_name), sheet = 1)


```

# DNK_Market_Sampling

```{r}

design_MS <-
  subset(design, DEsamplingScheme == "DNK_Market_Sampling")

samp_MS <- subset(samp, cruise %in% c("IN-HIRT", "IN-LYNG"))

# unique(samp_MS$targetSpecies1)

out <-
  subset(
    samp_MS,
    targetSpecies1 %in% c("BLH", "BRS", "TBM", "SPE", "HMK", "LOD", "MAK", "SIL", "PIL") |
      landingCategory %in% c("IND", "DIS") |
      speciesCode %in% c("MAK", "SIL") &
      landingCategory == "KON" | speciesCode == "GLL"
  )

out_sum <-
  summarise(
    group_by(out, speciesCode, targetSpecies1, landingCategory),
    kg = sum(weightTotal, na.rm = T)
  )

ok <- subset(samp_MS,!(sampleId %in% out$sampleId))

ok_sum <-
  summarise(
    group_by(ok, speciesCode, targetSpecies1, landingCategory),
    kg = sum(weightTotal, na.rm = T)
  )

samp_MS_ok <- distinct(ok, year, tripId, cruise, trip, harbourSample, dateSample)
ok$DEsamplingScheme <- "DNK_Market_Sampling"
ok$DEyear <- ok$year
ok$quarter <- quarter(ok$dateSample)
ok$stratumName <- "High activity"

samp_MS_ok_1 <- distinct(ok, DEyear, DEsamplingScheme, quarter, stratumName, tripId, cruise, trip)

design_MS_ok <- full_join(design_MS, samp_MS_ok_1)

rm(design_MS, ind, ind_sum, not_ind, not_ind_sum, ok, ok_sum, out, out_sum, samp_MS, samp_MS_ok, samp_MS_ok_1)

```


\newpage
# DNK_AtSea_Observer_Active

```{r}

design_AOA <-
  subset(design, DEsamplingScheme == "DNK_AtSea_Observer_Active")

samp_AOA <- subset(samp, cruise %in% c("MON", "SEAS"))

# 2018 ----
distinct(lh_18, Strata_Location, Strata_Gear, Strata_Area)

lh_18$Strata_Location[lh_18$Strata_Location == "Charlottenlund"] <- "Lyngby"

lh_18$stratumName <- gsub(" NA", "", paste(lh_18$Strata_Location, tolower(lh_18$Strata_Gear), lh_18$Strata_Area))

distinct(lh_18, stratumName)

lh_18$stratumName[lh_18$stratumName == "Lyngby hesterejer"] <- "Crangon"
lh_18$stratumName[lh_18$stratumName == "Hirtshals otb_cru_32-69_0_0"] <- "Pandalus"

test <- inner_join(lh_18, distinct(design, DEsamplingScheme, stratumName))

lh_18$fid <- lh_18$Fid
lh_18_ok <- distinct(lh_18, fid, stratumName)

# 2019 ----
distinct(lh_19, strata_location, strata_gear, strata_area)

lh_19$stratumName <- gsub(" NA", "", paste(lh_19$strata_location, gsub(" ", "", tolower(lh_19$strata_gear)), lh_19$strata_area))

distinct(lh_19, stratumName)

lh_19$stratumName[lh_19$stratumName == "Lyngby hesterejer"] <- "Crangon"
lh_19$stratumName[lh_19$stratumName == "Hirtshals otb_cru_32-69_0_0"] <- "Pandalus"

test <- inner_join(lh_19, distinct(design, DEsamplingScheme, stratumName))

unique(test$stratumName)

lh_19_ok <- distinct(lh_19, fid, stratumName)
```
